version: "2"
services:

  orion:
    image: fiware/orion-ld
    links:
      - mongo
    ports:
      - "1026:1026"
    networks:
      app_subnet:
        ipv4_address: 172.16.1.7
    command: -dbhost mongo

  mongo:
    image: mongo:3.6
    command: --nojournal
    ports:
      - '27017:27017'
    networks:
      app_subnet:
        ipv4_address: 172.16.1.6    
  

  openapithing:
    build: ./OpenAPI_WoT
    ports:
        - 5001:5000
    links: 
        - mongo
    depends_on:
        - mongo
    volumes:
        - ./OpenAPI_WoT:/code
    networks:
        app_subnet:
            ipv4_address: 172.16.1.9

  wotproxy:
      build: ./WoTproxy/
      ports:
          - 5002:5000
      links: 
          - orion
      networks:
          app_subnet:
              ipv4_address: 172.16.1.5

  nodered:
    build: ./nodered
    environment:
        - TZ=Europe/Amsterdam
    ports: 
        - "1880:1880"
    volumes:
        - node-red-data:/data
    links:
        - mongo
    networks:
        app_subnet:
            ipv4_address: 172.16.1.8

networks:
  app_subnet: 
    ipam:
        config: 
            - subnet: 172.16.1.0/24   

volumes:
  mysql-db:
  mongo:
  node-red-data: